import {
  SiReact,
  SiNextdotjs,
  SiTailwindcss,
  SiTypescript,
  SiJavascript,
  SiNodedotjs,
  SiExpress,
  SiPostgresql,
  SiSupabase,
  SiFramer,
  SiGit,
  SiPrisma,
  SiTrpc,
  SiPython,
  SiOpenai,
  SiExpo,
  SiBootstrap,
  SiHtml5,
  SiCss3,
  SiReactquery,
  SiMysql,
  SiFirebase,
  SiGithub,
  SiStripe,
  SiLangchain,
  SiShadcnui,
  SiVercel,
  SiDrizzle,
} from "react-icons/si";

// Split into two rows for the infinite scroll
export const techStackRow1 = [
  { icon: SiReact, name: "React" },
  { icon: SiNextdotjs, name: "Next.js" },
  { icon: SiTailwindcss, name: "Tailwind CSS" },
  { icon: SiTypescript, name: "TypeScript" },
  { icon: SiJavascript, name: "JavaScript" },
  { icon: SiNodedotjs, name: "Node.js" },
  { icon: SiExpress, name: "Express" },
  { icon: SiPostgresql, name: "PostgreSQL" },
  { icon: SiSupabase, name: "Supabase" },
  { icon: SiFramer, name: "Framer Motion" },
  { icon: SiGit, name: "Git" },
  { icon: SiShadcnui, name: "Shadcn UI" },
  { icon: SiReact, name: "React" },
  { icon: SiNextdotjs, name: "Next.js" },
  { icon: SiTailwindcss, name: "Tailwind CSS" },
  { icon: SiTypescript, name: "TypeScript" },
  { icon: SiJavascript, name: "JavaScript" },
  { icon: SiNodedotjs, name: "Node.js" },
  { icon: SiExpress, name: "Express" },
  { icon: SiPostgresql, name: "PostgreSQL" },
  { icon: SiSupabase, name: "Supabase" },
  { icon: SiGit, name: "Git" },
  { icon: SiPrisma, name: "Prisma ORM" },
  { icon: SiShadcnui, name: "Shadcn UI" },
  { icon: SiVercel, name: "Vercel" },
  { icon: SiDrizzle, name: "Drizzle ORM" },
];

export const techStackRow2 = [
  { icon: SiReact, name: "React" },
  { icon: SiNextdotjs, name: "Next.js" },
  { icon: SiTailwindcss, name: "Tailwind CSS" },
  { icon: SiTypescript, name: "TypeScript" },
  { icon: SiJavascript, name: "JavaScript" },
  { icon: SiNodedotjs, name: "Node.js" },
  { icon: SiExpress, name: "Express" },
  { icon: SiPostgresql, name: "PostgreSQL" },
  { icon: SiSupabase, name: "Supabase" },
  { icon: SiFramer, name: "Framer Motion" },
  { icon: SiGit, name: "Git" },
  { icon: SiPrisma, name: "Prisma ORM" },
  { icon: SiShadcnui, name: "Shadcn UI" },
  { icon: SiTrpc, name: "tRPC" },
  { icon: SiPython, name: "Python" },
  { icon: SiOpenai, name: "OpenAI" },
  { icon: SiExpo, name: "Expo" },
  { icon: SiBootstrap, name: "Bootstrap" },
  { icon: SiHtml5, name: "HTML5" },
  { icon: SiCss3, name: "CSS3" },
  { icon: SiReactquery, name: "React Query" },
  { icon: SiMysql, name: "MySQL" },
  { icon: SiGithub, name: "GitHub" },
  { icon: SiFirebase, name: "Firebase" },
  { icon: SiStripe, name: "Stripe" },
  { icon: SiLangchain, name: "LangChain" },
  { icon: SiVercel, name: "Vercel" },
  { icon: SiDrizzle, name: "Drizzle ORM" },
];
